"""
Security / sandboxing tests for the DuckDB-backed query engine.

These verify that SQL generated by an (untrusted) LLM cannot escape the data it
was given: no filesystem reads or writes, no network, no extension loading, no
re-enabling of the sandbox at runtime, plus resource guards (query timeout,
memory limit) and table-name injection defence.
"""

from __future__ import annotations

import os
import time

import duckdb
import pytest

from jsonflux import JsonFlux, QueryEngine, SecurityConfig

SAMPLE = [{"id": 1, "name": "Alice"}, {"id": 2, "name": "Bob"}]


@pytest.fixture
def engine():
    eng = QueryEngine().register("data", SAMPLE)
    yield eng
    eng.close()


# ---------------------------------------------------------------------------
# Filesystem reads are blocked
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "sql",
    [
        "SELECT content FROM read_text('/etc/passwd')",
        "SELECT * FROM read_csv('/etc/hostname')",
        "SELECT * FROM read_json('/etc/hostname')",
        "SELECT * FROM read_json_auto('/etc/hostname')",
        "SELECT file FROM glob('/etc/*')",
        "SELECT * FROM read_csv_auto('/etc/passwd')",
    ],
)
def test_filesystem_reads_blocked(engine, sql):
    with pytest.raises(duckdb.Error) as exc:
        engine.query(sql)
    # DuckDB raises a PermissionException / catalog/binder error, never returns data
    assert "passwd" not in str(exc.value) or "disabled" in str(exc.value).lower()


def test_read_passwd_does_not_leak_content(engine):
    """The strongest assertion: the file contents never come back."""
    try:
        rows = engine.query("SELECT content FROM read_text('/etc/passwd')")
    except Exception:
        return  # blocked as expected
    # If somehow it did not raise, it must not contain real passwd content.
    assert not any("root:" in str(r) for r in rows)


# ---------------------------------------------------------------------------
# Filesystem writes are blocked
# ---------------------------------------------------------------------------


def test_copy_to_file_blocked(engine, tmp_path):
    target = tmp_path / "leak.csv"
    with pytest.raises(duckdb.Error):
        engine.query(f"COPY (SELECT 1 AS x) TO '{target}' (FORMAT csv)")
    assert not target.exists()


def test_export_database_blocked(engine, tmp_path):
    with pytest.raises(duckdb.Error):
        engine.query(f"EXPORT DATABASE '{tmp_path}'")
    assert not any(os.scandir(tmp_path)) if tmp_path.exists() else True


# ---------------------------------------------------------------------------
# Extensions / attach / network
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "sql",
    [
        "INSTALL httpfs",
        "LOAD httpfs",
        "INSTALL spatial",
        "ATTACH '/tmp/other.db' AS other",
        "ATTACH 'https://example.com/x.db' AS other",
    ],
)
def test_extensions_and_attach_blocked(engine, sql):
    with pytest.raises(duckdb.Error):
        engine.query(sql)


# ---------------------------------------------------------------------------
# The sandbox cannot be relaxed at runtime
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "sql",
    [
        "SET enable_external_access=true",
        "PRAGMA enable_external_access=true",
        "SET GLOBAL enable_external_access=true",
        "SET lock_configuration=false",
    ],
)
def test_cannot_reenable_access(engine, sql):
    with pytest.raises(duckdb.Error):
        engine.query(sql)
    # And a read is still blocked afterwards.
    with pytest.raises(duckdb.Error):
        engine.query("SELECT content FROM read_text('/etc/hostname')")


# ---------------------------------------------------------------------------
# Legitimate queries keep working under the sandbox
# ---------------------------------------------------------------------------


def test_legit_queries_work(engine):
    assert engine.query("SELECT name FROM data WHERE id = 1") == [{"name": "Alice"}]
    assert engine.query("SELECT count(*) AS c FROM data") == [{"c": 2}]
    agg = engine.query("SELECT sum(id) AS s, avg(id) AS a FROM data")
    assert agg[0]["s"] == 3


def test_jsonflux_query_is_sandboxed():
    flux = JsonFlux().analyze({"users": [{"id": 1, "score": 95}]})
    with pytest.raises(duckdb.Error):
        flux.query("SELECT content FROM read_text('/etc/passwd')")
    # normal query still works
    rows = flux.query("SELECT u.score FROM (SELECT unnest(users) u FROM data)")
    assert rows == [{"score": 95}]
    flux.close()


# ---------------------------------------------------------------------------
# Opt-in escape hatch
# ---------------------------------------------------------------------------


def test_allow_external_access_opt_in(tmp_path):
    f = tmp_path / "hello.txt"
    f.write_text("hello world")
    eng = QueryEngine(allow_external_access=True).register("data", SAMPLE)
    try:
        rows = eng.query(f"SELECT content FROM read_text('{f}')")
        assert rows[0]["content"] == "hello world"
    finally:
        eng.close()


def test_security_config_object_passthrough(tmp_path):
    f = tmp_path / "hi.txt"
    f.write_text("hi")
    cfg = SecurityConfig(allow_external_access=True)
    eng = QueryEngine(security=cfg).register("data", SAMPLE)
    try:
        assert eng.query(f"SELECT content FROM read_text('{f}')")[0]["content"] == "hi"
    finally:
        eng.close()


# ---------------------------------------------------------------------------
# Resource guards
# ---------------------------------------------------------------------------


def test_query_timeout_interrupts_runaway_query():
    eng = QueryEngine(query_timeout=0.5).register("data", SAMPLE)
    try:
        t0 = time.perf_counter()
        with pytest.raises(TimeoutError):
            eng.query("SELECT count(*) FROM range(100000000000) a, range(100000) b")
        elapsed = time.perf_counter() - t0
        assert elapsed < 5.0  # interrupted quickly, not run to completion
        # Connection is reusable after an interrupt.
        assert eng.query("SELECT 1 AS x") == [{"x": 1}]
    finally:
        eng.close()


def test_timeout_none_disables_watchdog():
    eng = QueryEngine(security=SecurityConfig(query_timeout=None)).register(
        "data", SAMPLE
    )
    try:
        assert eng.query("SELECT count(*) AS c FROM data")[0]["c"] == 2
    finally:
        eng.close()


def test_memory_limit_applied():
    eng = QueryEngine(memory_limit="512MB").register("data", SAMPLE)
    try:
        setting = eng.query("SELECT current_setting('memory_limit') AS m")[0]["m"]
        # DuckDB reports it in MiB; just assert it is a bounded, small value.
        assert "GiB" not in setting or setting.startswith("0")
    finally:
        eng.close()


# ---------------------------------------------------------------------------
# Table-name injection defence
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "bad_name",
    [
        "data; DROP TABLE data",
        "data--",
        "1data",
        "data table",
        "data'",
        "",
        "read_text",  # ok chars but still fine; keep as sanity for underscores
    ],
)
def test_invalid_table_names(bad_name):
    eng = QueryEngine()
    try:
        if bad_name == "read_text":
            # This IS a valid identifier and should be accepted.
            eng.register(bad_name, SAMPLE)
        else:
            with pytest.raises(ValueError):
                eng.register(bad_name, SAMPLE)
    finally:
        eng.close()


# ---------------------------------------------------------------------------
# Config rendering
# ---------------------------------------------------------------------------


def test_security_config_defaults_are_locked():
    cfg = SecurityConfig().to_duckdb_config()
    assert cfg["enable_external_access"] == "false"
    assert cfg["lock_configuration"] == "true"
    assert cfg["autoinstall_known_extensions"] == "false"
    assert cfg["allow_community_extensions"] == "false"


def test_security_config_permissive():
    cfg = SecurityConfig(
        allow_external_access=True,
        allow_extensions=True,
        lock_configuration=False,
        memory_limit=None,
    ).to_duckdb_config()
    assert "enable_external_access" not in cfg
    assert "lock_configuration" not in cfg
    assert "memory_limit" not in cfg


def test_connection_actually_locked():
    """Independent proof that lock_configuration is in force on the raw conn."""
    eng = QueryEngine()
    try:
        with pytest.raises(duckdb.InvalidInputException):
            eng.conn.execute("SET enable_external_access=true")
    finally:
        eng.close()
